name = "jiwonz/go"
version = "0.1.0"
description = "Execute the functions in a separate thread, threads are pooled and reused. Credit to lukadev-0/util.luau"
authors = ["LukaDev <luka@lukadev.me> (https://lukadev.me/)", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/luau-go"
license = "MIT"
includes = ["pesde.toml", "README.md", "lib.luau", "LICENSE"]

[target]
environment = "luau"
lib = "lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.3.7", target = "lune" }
